# Generated by Dock-u-Pilot 🐳
# An intelligent Docker configuration generator
# Repository: https://github.com/your-org/dock-u-pilot
# Generated on: 2025-06-19 16:29:24 UTC
# 
# This configuration has been optimized for security, performance, and best practices
# Review and customize as needed for your specific requirements

# Generic Application Dockerfile
FROM alpine:latest

# Security: Consider running security scans
# RUN apt-get update && apt-get install -y --no-install-recommends curl \
#     && curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin \
#     && grype . && rm /usr/local/bin/grype \
#     && apt-get remove -y curl && apt-get autoremove -y



# Install basic tools
RUN apk add --no-cache curl

# Create app directory
WORKDIR /usr/src/app

# Create non-root user
RUN adduser -D -s /bin/sh -u 1001 appuser

# Copy application files
COPY --chown=appuser:appuser . .

# Switch to non-root user
USER appuser

# Expose port
EXPOSE 8080

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:8080/health || exit 1

# Default command (customize as needed)
CMD ["echo", "Please customize this Docker configuration for your application"]
