[build]
command = "hugo --gc --minify"
publish = "public"

[build.environment]
NODE_VERSION = "22.2.0"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV           = "production"
HUGO_THEME         = "toha"
HUGO_VERSION       = "0.127.1"
NODE_VERSION       = "22.2.0"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
  HUGO_ENV     = "production"
  HUGO_VERSION = "0.127.1"
  NODE_VERSION = "22.2.0"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

  [context.deploy-preview.environment]
  HUGO_VERSION = "0.127.1"
  NODE_VERSION = "22.2.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

  [context.branch-deploy.environment]
  HUGO_VERSION = "0.127.1"
  NODE_VERSION = "22.2.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
NODE_VERSION       = "22.2.0"
